MAX_NAME_LENGTH = 256
MAX_SLUG_ROLE_LENGTH = 50
MAX_USERNAME_FIRST_NAME_LAST_NAME_LENGTH = 150
MAX_EMAIL_LENGTH = 254
MIN_YEAR_VALUE_VALIDATOR = 1800
MIN_SCORE_VALUE_VALIDATOR = 1
MAX_SCORE_VALUE_VALIDATOR = 10
